appraise "cucumber-latest" do
  gem "cucumber"
end

appraise "cucumber-2.4.0" do
  gem "cucumber", "2.4.0"
end

appraise "cucumber-2.0.1" do
  gem "cucumber", "2.0.1"
end

appraise "cucumber-1.3.20" do
  gem "cucumber", "1.3.20"
end

appraise "cucumber-1.2.0" do
  gem "cucumber", "1.2.0"
end
